package com.test;
 dialect "mvel" 
 
rule "ageRule_51"
    when
        $x :  com.geeks18.virtualserver.drools.model.OrderRequest(orderId == "10" && OrderName == "Meat" && Count == "4" )
        $y :  com.geeks18.virtualserver.drools.model.OrderResponse();
    then
     $y.setOrderId("10");$y.setPrice("100");$y.setTest("Aritra");;
end



rule "ageRule_52"
    when
        $x :  com.geeks18.virtualserver.drools.model.OrderRequest(orderId == "20" && OrderName == "Soap" && Count == "3" )
        $y :  com.geeks18.virtualserver.drools.model.OrderResponse();
    then
     $y.setOrderId("20");$y.setPrice("200");$y.setTest("Joy");;
end



rule "ageRule_53"
    when
        $x :  com.geeks18.virtualserver.drools.model.OrderRequest(orderId == "30" && OrderName == "Pen" && Count == "2" )
        $y :  com.geeks18.virtualserver.drools.model.OrderResponse();
    then
     $y.setOrderId("30");$y.setPrice("300");$y.setTest("Rana");;
end


